version: '3'
services:
  api:
    image: 'node:12.18.4'
    working_dir: /code
    ports:
      - 5000:5000
    environment:
      - PGUSER= Citizenspoll
      - PGHOST= db
      - PGPASSWORD=TurkeyOwnsBaklava
      - PGDATABASE=database
      - PGPORT=5432
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"
  db:
    image: 'postgres:11.1'
    expose:
      - '5432'
    volumes:
      - 'databasedata:/var/lib/postgresql/data'
      - './db:/docker-entrypoint-initdb.d/:ro'
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=Citizenspoll
      - POSTGRES_PASSWORD=TurkeyOwnsBaklava
volumes:
  databasedata:
